# Generated by Django 2.2.24 on 2021-10-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fkult', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fkult.Season'),
        ),
    ]
