repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        args: [--target-version, py311, --line-length, "120", --skip-string-normalization]
        exclude: '(migrations|urls\.py)'
        files: '^(stregsystem|stregreport|kiosk|razzia|achievements|events)/'

