FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD sh -c "printf '[database]\nengine=django.db.backends.postgresql\nname=${POSTGRES_DB}\nuser=${POSTGRES_USER}\npassword=${POSTGRES_PASSWORD}\nhost=${POSTGRES_HOST}\nport=5432\n' > local.cfg && \
    python manage.py migrate --noinput"