# Generated by Django 4.1.13 on 2025-05-12 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stregsystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Razzia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("turns_per_member", models.IntegerField(default=0)),
                ("turn_interval", models.DurationField(default=datetime.timedelta(0))),
                ("start_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "permissions": (("browse_razzia", "Can browse razzias"),),
            },
        ),
        migrations.CreateModel(
            name="RazziaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stregsystem.member",
                    ),
                ),
                (
                    "razzia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="razzia.razzia"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="razzia",
            name="members",
            field=models.ManyToManyField(
                through="razzia.RazziaEntry", to="stregsystem.member"
            ),
        ),
    ]
