# Generated by Django 4.1.13 on 2024-09-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "stregsystem",
            "0018_member_signup_due_paid_alter_mobilepayment_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Razzia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("turn_interval", models.DurationField(default=0)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "permissions": (
                    ("host_razzia", "Can host a foobar, fnugfald or bread razzia"),
                ),
            },
        ),
        migrations.CreateModel(
            name="RazziaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stregsystem.member",
                    ),
                ),
                (
                    "razzia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="razzia.razzia"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="razzia",
            name="members",
            field=models.ManyToManyField(
                through="razzia.RazziaEntry", to="stregsystem.member"
            ),
        ),
    ]
