# Generated by Django 4.1.13 on 2024-11-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("razzia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="razzia",
            options={"permissions": (("browse_razzia", "Can browse razzias"),)},
        ),
    ]
