# Generated by Django 4.1.13 on 2024-09-14 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("razzia", "0002_razzia_turns_per_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razzia",
            name="turn_interval",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
