# Generated by Django 4.1.13 on 2025-09-03 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("razzia", "0002_alter_razzia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="razzia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="razzia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
