# Generated by Django 4.1.13 on 2026-03-10 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("razzia", "0002_alter_razzia_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="razzia",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    1976, 2, 1, 0, 0, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="razzia",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
