# Generated by Django 2.2.28 on 2024-02-29 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stregsystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('year', models.CharField(default=stregsystem.models.get_current_year, max_length=4)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('U', 'Unknown'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('want_spam', models.BooleanField(default=True)),
                ('balance', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('alcohol_content_ml', models.FloatField(default=0.0, null=True)),
                ('caffeine_content_mg', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='stregsystem.Category')),
                ('rooms', models.ManyToManyField(blank=True, to='stregsystem.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Member')),
            ],
            options={
                'permissions': (('import_batch_payments', 'Import batch payments'),),
            },
        ),
        migrations.CreateModel(
            name='OldPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_prices', to='stregsystem.Product')),
            ],
        ),
        migrations.CreateModel(
            name='NamedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[^\\d:\\-_][\\w\\-]+$')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_id', to='stregsystem.Product')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('U', 'Unset'), ('A', 'Approved'), ('I', 'Ignored')], default='U', max_length=1)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Member')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Payment')),
            ],
            options={
                'permissions': (('mobilepaytool_access', 'MobilePaytool access'),),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Product')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Room')),
            ],
            options={
                'permissions': (('access_sales_reports', 'Can access sales reports'),),
                'index_together': {('product', 'timestamp')},
            },
        ),
    ]
