# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
