# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
