# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol_content_ml',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
