# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0004_product_alcohol_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='stregsystem.Room'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='stregsystem.Category'),
        ),
    ]
