# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0007_change_bought_to_limit_start_date'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='sale',
            index_together=set([('product', 'timestamp')]),
        ),
    ]
