# Generated by Django 2.2.8 on 2020-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0009_auto_20191028_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('import_batch_payments', 'Import batch payments'),)},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('access_sales_reports', 'Can access sales reports'),)},
        ),
    ]
