# Generated by Django 2.2.8 on 2020-10-02 11:33

from django.db import migrations, models

def copy_id_to_custom_id(apps, schema_editor):
    Product = apps.get_model('stregsystem', 'Product')
    for product in Product.objects.all():
        product.custom_id = product.id
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0010_auto_20200305_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(copy_id_to_custom_id),
        migrations.AlterField(
            model_name='product',
            name='custom_id',
            field=models.IntegerField(unique=True),
        )
    ]
