# Generated by Django 2.2.8 on 2020-09-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0010_auto_20200305_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=32, unique=True)),
                ('comment', models.CharField(max_length=128)),
                ('approval', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Member')),
                ('member_guess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_guess', to='stregsystem.Member')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Payment')),
            ],
        ),
    ]
