# Generated by Django 2.2.8 on 2020-10-24 14:28

from django.db import migrations, models
import stregsystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0010_auto_20200305_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(default=stregsystem.models.get_current_year, max_length=4),
        ),
    ]
