# Generated by Django 2.2.8 on 2020-09-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0011_auto_20200908_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(default='2020', max_length=4),
        ),
    ]
