# Generated by Django 2.2.13 on 2020-11-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0012_mobilepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilepayment',
            options={'permissions': (('mobilepaytool_access', 'MobilePaytool access'),)},
        ),
    ]
