# Generated by Django 2.2.24 on 2021-09-11 13:08

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0014_mobilepayment_nullable_customername_20210908_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilepayment',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
