# Generated by Django 2.2.13 on 2021-09-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0015_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='parent_item',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_item',
            field=models.ManyToManyField(blank=True, to='stregsystem.InventoryItem'),
        ),
    ]
