# Generated by Django 2.2.24 on 2022-04-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0015_product_caffeine_content_mg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('ticket_start_threshold', models.DateTimeField()),
                ('ticket_end_threshold', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Product')),
            ],
        ),
    ]
