# Generated by Django 2.2.24 on 2021-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0015_product_caffine_content_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='caffine_content_ml',
        ),
        migrations.AddField(
            model_name='product',
            name='caffeine_content_mg',
            field=models.IntegerField(default=0),
        ),
    ]
