# Generated by Django 2.2.13 on 2021-10-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0016_auto_20210930_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_item',
            new_name='sub_items',
        ),
    ]
