# Generated by Django 2.2.24 on 2022-05-11 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0016_namedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedproduct',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[^\\d:\\-_][\\w\\-]+$')]),
        ),
    ]
