# Generated by Django 2.2.24 on 2022-04-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0015_product_caffeine_content_mg'),
        ('stregsystem', '0016_event_active'),
    ]

    operations = [
    ]
