# Generated by Django 2.2.28 on 2024-04-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0017_auto_20220511_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='requested_data_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
