# Generated by Django 2.2.13 on 2021-10-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0017_auto_20211004_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
