# Generated by Django 2.2.28 on 2024-04-30 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0017_auto_20220511_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='signup_due_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.IntegerField(default=20000)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregsystem.Member')),
            ],
        ),
    ]
