# Generated by Django 2.2.13 on 2021-10-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0018_inventoryitem_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
    ]
