# Generated by Django 2.2.28 on 2024-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0019_auto_20240427_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='requested_data_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
