# Generated by Django 2.2.13 on 2021-10-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0019_remove_inventoryitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_items',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='products',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='stregsystem.Product'),
            preserve_default=False,
        ),
    ]
