# Generated by Django 4.1.13 on 2024-10-24 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0019_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_username', regex='^\\S+$')]),
        ),
    ]
