# Generated by Django 4.1.13 on 2024-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0020_alter_member_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="kiosk_mode",
            field=models.BooleanField(default=True),
        ),
    ]
