# Generated by Django 2.2.13 on 2021-10-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0020_auto_20211004_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='stregsystem.Product'),
        ),
    ]
