# Generated by Django 2.2.13 on 2021-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0021_auto_20211004_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
