# Generated by Django 4.1.13 on 2025-01-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0022_productnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="name_style",
            field=models.TextField(
                blank=True,
                help_text="If product is very cool, usually something like: font-size: 2em; font-weight: bold; color: red; margin: 1em 0;",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="productnote",
            name="background_color",
            field=models.CharField(
                default="yellow", help_text="Write a valid html color", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="productnote",
            name="text_color",
            field=models.CharField(
                default="black", help_text="Write a valid html color", max_length=20
            ),
        ),
    ]
