# Generated by Django 2.2.13 on 2021-10-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0022_inventorystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystatus',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_status', to='stregsystem.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorystatus',
            name='product_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorystatus',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
