# Generated by Django 4.1.13 on 2025-04-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0023_achievement_achievementtask_achievementmember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementtask",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="achievementtask",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stregsystem.category",
            ),
        ),
        migrations.AddField(
            model_name="achievementtask",
            name="task_type",
            field=models.CharField(default="default", max_length=50),
        ),
        migrations.AlterField(
            model_name="achievementtask",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stregsystem.product",
            ),
        ),
    ]
