# Generated by Django 2.2.13 on 2021-10-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0023_auto_20211006_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_out_date',
        ),
        migrations.DeleteModel(
            name='InventoryStatus',
        ),
    ]
