# Generated by Django 4.1.13 on 2026-03-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0023_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productnote",
            name="products",
            field=models.ManyToManyField(blank=True, to="stregsystem.product"),
        ),
    ]
