# Generated by Django 4.1.13 on 2026-03-21 22:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0024_alter_productnote_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("buystring", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("C", "Confirmed"),
                            ("A", "Aborted"),
                            ("F", "Finalized"),
                            ("R", "Removed"),
                            ("E", "Expired"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stregsystem.room",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
