# Generated by Django 4.1.13 on 2025-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0024_remove_achievementtask_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementmember",
            name="progress_count",
            field=models.FloatField(default=0),
        ),
    ]
