# Generated by Django 2.2.13 on 2021-10-06 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0024_auto_20211006_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_quantity', models.IntegerField(default=0)),
                ('old_quantity', models.IntegerField(default=0)),
                ('count_date', models.DateField(default=datetime.date(2021, 10, 6))),
                ('sold_out', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_history', to='stregsystem.InventoryItem')),
            ],
        ),
    ]
