# Generated by Django 4.1.13 on 2026-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0025_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="intent",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intent",
            name="return_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
