# Generated by Django 2.2.13 on 2021-10-06 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0025_inventoryitemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemhistory',
            name='count_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 15, 54, 48, 349866, tzinfo=utc)),
        ),
    ]
