# Generated by Django 4.1.13 on 2025-04-18 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0025_alter_achievementmember_progress_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="active_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="day_of_month",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="weekday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="achievementtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("any", "Any"),
                    ("balance", "Balance"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="achievementtask",
            unique_together={("achievement", "product", "category", "task_type")},
        ),
    ]
