# Generated by Django 4.1.13 on 2026-04-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0026_intent_fulfilled_at_intent_return_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intent",
            old_name="buystring",
            new_name="product_string",
        ),
        migrations.AddField(
            model_name="intent",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stregsystem.member",
            ),
        ),
        migrations.AlterField(
            model_name="intent",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stregsystem.room"
            ),
        ),
        migrations.AlterField(
            model_name="intent",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initiated"),
                    ("P", "Pending"),
                    ("F", "Finalized"),
                    ("A", "Aborted"),
                    ("C", "Cancelled"),
                    ("E", "Expired"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
