# Generated by Django 2.2.13 on 2021-10-06 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0026_auto_20211006_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemhistory',
            name='count_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
