# Generated by Django 4.1.13 on 2025-04-19 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "stregsystem",
            "0026_achievement_active_duration_achievement_date_end_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="active_duration",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="date_start",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="day_of_month",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="time_end",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="time_start",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="weekday",
        ),
        migrations.AddField(
            model_name="achievement",
            name="globally_active_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="globally_active_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AchievementConstraint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("max_duration", models.DurationField(blank=True, null=True)),
                (
                    "weekday",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_constraints",
                        to="stregsystem.achievement",
                    ),
                ),
            ],
        ),
    ]
