# Generated by Django 4.1.13 on 2025-04-19 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0027_remove_achievement_active_duration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievementconstraint",
            old_name="day_of_month",
            new_name="day_end",
        ),
        migrations.RemoveField(
            model_name="achievementconstraint",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="achievementconstraint",
            name="date_start",
        ),
        migrations.AddField(
            model_name="achievementconstraint",
            name="day_start",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="achievementconstraint",
            name="month_end",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="achievementconstraint",
            name="month_start",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="achievementconstraint",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stregsystem.achievement",
            ),
        ),
    ]
