# Generated by Django 2.2.13 on 2021-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0027_auto_20211006_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitemhistory',
            options={'verbose_name_plural': 'Inventory History'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='desired_amount',
            field=models.IntegerField(default=0),
        ),
    ]
