# Generated by Django 4.1.13 on 2026-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stregsystem",
            "0027_rename_buystring_intent_product_string_intent_member_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="intent",
            name="status",
            field=models.CharField(
                choices=[
                    ("I", "Initiated"),
                    ("P", "Pending"),
                    ("F", "Finalized"),
                    ("A", "Aborted"),
                    ("C", "Cancelled"),
                    ("E", "Expired"),
                ],
                default="I",
                max_length=1,
            ),
        ),
    ]
