# Generated by Django 4.1.13 on 2026-04-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0028_alter_intent_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intent",
            name="fulfilled_at",
        ),
    ]
