# Generated by Django 2.2.13 on 2021-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0028_auto_20211006_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemhistory',
            name='loss',
            field=models.IntegerField(default=0),
        ),
    ]
