# Generated by Django 4.1.13 on 2025-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stregsystem",
            "0028_rename_day_of_month_achievementconstraint_day_end_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="achievementmember",
            name="begun_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
