# Generated by Django 4.1.13 on 2025-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0029_achievementmember_begun_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementconstraint",
            name="max_duration",
        ),
        migrations.AddField(
            model_name="achievement",
            name="max_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
