# Generated by Django 2.2.13 on 2021-10-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0029_inventoryitemhistory_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitemhistory',
            name='sold_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
