# Generated by Django 4.1.13 on 2025-04-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0030_remove_achievementconstraint_max_duration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievementmember",
            old_name="begun_at",
            new_name="last_progress_at",
        ),
    ]
