# Generated by Django 2.2.13 on 2021-10-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0030_auto_20211008_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold_out_date',
        ),
    ]
