# Generated by Django 4.1.13 on 2025-04-29 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0031_rename_begun_at_achievementmember_last_progress_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementmember",
            name="last_progress_at",
        ),
        migrations.RemoveField(
            model_name="achievementmember",
            name="progress_count",
        ),
        migrations.AddField(
            model_name="achievementmember",
            name="begin_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
