# Generated by Django 4.1.13 on 2025-04-30 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0032_remove_achievementmember_last_progress_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementComplete",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="achievement",
            name="begin_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AchievementMember",
        ),
        migrations.AddField(
            model_name="achievementcomplete",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stregsystem.achievement",
            ),
        ),
        migrations.AddField(
            model_name="achievementcomplete",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stregsystem.member"
            ),
        ),
    ]
