# Generated by Django 4.1.13 on 2025-05-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0033_achievementcomplete_achievement_begin_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="max_duration",
            new_name="duration",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="globally_active_from",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="globally_active_until",
        ),
        migrations.AlterUniqueTogether(
            name="achievementcomplete",
            unique_together={("member", "achievement")},
        ),
    ]
