# Generated by Django 4.1.13 on 2025-05-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0034_rename_max_duration_achievement_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("any", "Any"),
                    ("used_funds", "Used Funds"),
                    ("remaining_funds", "Remaining Funds"),
                    ("stregforbud", "Stregforbud"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
