# Generated by Django 4.1.13 on 2025-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0035_alter_achievementtask_task_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="achievementtask",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="achievementtask",
            name="alcohol_content",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievementtask",
            name="caffeine_content",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
