# Generated by Django 4.1.13 on 2025-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0036_alter_achievementtask_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievementtask",
            old_name="alcohol_content",
            new_name="alcohol_content_ml",
        ),
        migrations.RenameField(
            model_name="achievementtask",
            old_name="caffeine_content",
            new_name="caffeine_content_mg",
        ),
        migrations.AlterField(
            model_name="achievementtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("any", "Any"),
                    ("used_funds", "Used Funds"),
                    ("remaining_funds", "Remaining Funds"),
                ],
                default="default",
                max_length=50,
            ),
        ),
    ]
