# Generated by Django 4.1.13 on 2025-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stregsystem",
            "0037_rename_alcohol_content_achievementtask_alcohol_content_ml_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementtask",
            name="alcohol_content_ml",
        ),
        migrations.RemoveField(
            model_name="achievementtask",
            name="caffeine_content_mg",
        ),
        migrations.AddField(
            model_name="achievementtask",
            name="alcohol_content",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="achievementtask",
            name="caffeine_content",
            field=models.BooleanField(default=True),
        ),
    ]
