# Generated by Django 4.1.13 on 2025-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stregsystem", "0038_remove_achievementtask_alcohol_content_ml_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementtask",
            name="alcohol_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="achievementtask",
            name="caffeine_content",
            field=models.BooleanField(default=False),
        ),
    ]
