# Generated by Django 4.1.13 on 2026-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberotprequest",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="memberotprequest",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
