# Generated by Django 4.1.13 on 2026-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membersso",
            name="username",
            field=models.CharField(default="a", max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
