# Generated by Django 4.1.13 on 2025-05-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stregsystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreadRazzia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "razzia_type",
                    models.CharField(
                        choices=[
                            ("BR", "Brødrazzia"),
                            ("FB", "Foobar razzia"),
                            ("FF", "Fnugfald razzia"),
                        ],
                        default="BR",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("host_razzia", "Can host a foobar, fnugfald or bread razzia"),
                ),
            },
        ),
        migrations.CreateModel(
            name="RazziaEntryOld",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stregsystem.member",
                    ),
                ),
                (
                    "razzia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stregreport.breadrazzia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="breadrazzia",
            name="members",
            field=models.ManyToManyField(
                through="stregreport.RazziaEntryOld", to="stregsystem.member"
            ),
        ),
    ]
