# Generated by Django 2.2.5 on 2019-10-28 20:58

from django.db import migrations

def create_razzia_through_field(apps, schema_editor):
	BreadRazzia = apps.get_model('stregreport', 'BreadRazzia')
	RazziaEntry = apps.get_model('stregreport', 'RazziaEntry')

	for razzia in BreadRazzia.objects.all():
		for member in razzia.members.all():
			RazziaEntry(member = member, razzia = razzia, time=razzia.start_date).save()

class Migration(migrations.Migration):

    dependencies = [
        ('stregreport', '0002_razziaentry'),
    ]

    operations = [
    	migrations.RunPython(create_razzia_through_field, reverse_code=migrations.RunPython.noop)
    ]
