# Generated by Django 2.2.5 on 2019-10-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregreport', '0003_auto_20191028_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadrazzia',
            name='members',
        ),
    ]
