# Generated by Django 2.2.5 on 2019-10-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregreport', '0005_breadrazzia_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadrazzia',
            name='razzia_type',
            field=models.CharField(choices=[('BR', 'Brødrazzia'), ('FB', 'Foobar razzia')], default='BR', max_length=2),
        ),
    ]
