# Generated by Django 2.2.8 on 2020-03-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregreport', '0006_breadrazzia_razzia_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadrazzia',
            options={'permissions': (('host_razzia', 'Can host a foobar or bread razzia'),)},
        ),
    ]
