# Generated by Django 4.1.13 on 2024-05-21 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stregreport", "0008_auto_20231103_1126"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="razziaentry",
            name="member",
        ),
        migrations.RemoveField(
            model_name="razziaentry",
            name="razzia",
        ),
        migrations.DeleteModel(
            name="BreadRazzia",
        ),
        migrations.DeleteModel(
            name="RazziaEntry",
        ),
    ]
