# Generated by Django 2.2.28 on 2023-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregreport', '0008_auto_20231103_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadrazzia',
            options={'permissions': (('host_razzia', 'Can host a foobar or bread razzia'),)},
        ),
        migrations.AlterField(
            model_name='breadrazzia',
            name='razzia_type',
            field=models.CharField(choices=[('BR', 'Brødrazzia'), ('FB', 'Foobar razzia')], default='BR', max_length=2),
        ),
    ]
