name: OpenAPI Validation & HTTP Test

on:
  push:
    branches:
      - master
      - next
  pull_request:

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r openapi/requirements.txt
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm i -g dredd
    - run: dredd --config openapi/dredd.yml
