# Generated by Django 4.1.13 on 2025-05-14 07:58

from django.db import migrations, models
import kiosk.models
import kiosk.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KioskItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.CharField(blank=True, max_length=2000, null=True)),
                ("uploaded_date", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "media",
                    models.FileField(
                        upload_to="kiosk",
                        validators=[kiosk.validators.validate_file_extension],
                    ),
                ),
                ("ordering", models.IntegerField(default=kiosk.models.random_ordering)),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
