# Generated by Django 2.2.8 on 2020-11-12 17:12

from django.db import migrations, models
import kiosk.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_kioskitem_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskitem',
            name='media',
            field=models.FileField(default='static/kiosk/kioskbg.png', upload_to='kiosk', validators=[kiosk.validators.validate_file_extension]),
        ),
    ]
