# Generated by Django 2.2.8 on 2020-10-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_kioskitem_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskitem',
            name='image',
            field=models.FileField(upload_to='kiosk'),
        ),
    ]
