# Generated by Django 2.0.2 on 2018-04-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kiosk', '0003_kioskitem_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskitem',
            name='image',
        ),
        migrations.CreateModel(
            name='KioskImage',
            fields=[
                ('kioskitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosk.KioskItem')),
                ('image', models.ImageField(upload_to='kiosk')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kiosk.kioskitem',),
        ),
        migrations.CreateModel(
            name='KioskVideo',
            fields=[
                ('kioskitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosk.KioskItem')),
                ('video', models.FileField(upload_to='kiosk')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('kiosk.kioskitem',),
        ),
        migrations.AlterModelOptions(
            name='kioskitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='kioskitem',
            name='duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='kioskitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kiosk.kioskitem_set+', to='contenttypes.ContentType'),
        ),
    ]
