# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kiosk', '0003_kioskitem_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskitem',
            name='image',
        ),
        migrations.CreateModel(
            name='KioskImageItem',
            fields=[
                ('kioskitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosk.KioskItem')),
                ('image', models.ImageField(upload_to='kiosk')),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosk.kioskitem',),
        ),
        migrations.CreateModel(
            name='KioskWebsiteItem',
            fields=[
                ('kioskitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosk.KioskItem')),
                ('url', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
            bases=('kiosk.kioskitem',),
        ),
        migrations.AddField(
            model_name='kioskitem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kiosk.kioskitem_set+', to='contenttypes.ContentType'),
        ),
    ]
