# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import kiosk.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_kioskitem_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteKioskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=kiosk.models.random_ordering)),
                ('url', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='KioskItem',
            new_name='KioskImageItem',
        ),
    ]
