# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import kiosk.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kiosk', '0004_auto_20171117_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=kiosk.models.random_ordering)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kiosk.kioskitem_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='kioskimageitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='kioskimageitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kioskimageitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kioskimageitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='kioskimageitem',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='kioskimageitem',
            name='uploaded_date',
        ),
        migrations.RemoveField(
            model_name='websitekioskitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='websitekioskitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='websitekioskitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='websitekioskitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='websitekioskitem',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='websitekioskitem',
            name='uploaded_date',
        ),
        migrations.AddField(
            model_name='kioskimageitem',
            name='kioskitem_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosk.KioskItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitekioskitem',
            name='kioskitem_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiosk.KioskItem'),
            preserve_default=False,
        ),
    ]
