# Generated by Django 2.2.8 on 2020-10-10 14:58

from django.db import migrations, models
import kiosk.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20201009_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskitem',
            name='media',
            field=models.FileField(default='', upload_to='kiosk', validators=[kiosk.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='kioskitem',
            name='image',
            field=models.FileField(upload_to='kiosk', validators=[kiosk.validators.validate_file_extension]),
        ),
    ]
