# Generated by Django 2.2.8 on 2020-10-10 14:59

from django.db import migrations


def migrate_all_data(apps, schema_editor):
    KioskItem = apps.get_model('kiosk', 'KioskItem')
    for x in KioskItem.objects.all():
        x.media = x.image
        x.save()


def reverse_migrate_all_data(apps, schema_editor):
    """
    This is for using the migrate
    """
    KioskItem = apps.get_model('kiosk', 'KioskItem')
    for x in KioskItem.objects.all():
        x.image = x.media
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_auto_20201010_1458'),
    ]

    operations = [
        migrations.RunPython(migrate_all_data, reverse_migrate_all_data)
    ]
