# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_auto_20171117_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteKioskItem',
            new_name='KioskWebsiteItem',
        ),
    ]
