# Generated by Django 2.2.8 on 2020-10-11 18:04

from django.db import migrations, models
import kiosk.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_auto_20201010_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='kioskitem',
            name='media',
            field=models.FileField(upload_to='kiosk', validators=[kiosk.validators.validate_file_extension]),)

    ]
