# Generated by Django 2.2.28 on 2023-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0006_remove_image_20201112_1715"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kioskitem",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
