# Generated by Django 2.2.28 on 2023-08-18 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_remove_image_20201112_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='kioskitem',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kioskitem',
            name='start_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 18, 12, 31, 12, 792200, tzinfo=utc)),
        ),
    ]
