# Generated by Django 4.1.13 on 2025-04-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0007_auto_20230823_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
