# Generated by Django 4.1.13 on 2025-09-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0007_auto_20230823_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
