# Generated by Django 4.1.13 on 2025-09-18 01:42

from django.db import migrations, models
import kiosk.validators


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0007_auto_20230823_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="website_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="kioskitem",
            name="media",
            field=models.FileField(
                blank=True,
                upload_to="kiosk",
                validators=[kiosk.validators.validate_file_extension],
            ),
        ),
    ]
