# Generated by Django 4.1.13 on 2025-10-30 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0008_kioskitem_website_url_alter_kioskitem_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="duration",
            field=models.IntegerField(
                default=10000,
                validators=[django.core.validators.MinValueValidator(1000)],
                verbose_name="Duration (ms)",
            ),
        ),
    ]
