# Generated by Django 4.1.13 on 2025-04-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0008_kioskitem_website_url_alter_kioskitem_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="duration",
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
    ]
