# Generated by Django 4.1.13 on 2025-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0008_kioskitem_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kioskitem",
            name="duration",
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
    ]
