# Generated by Django 4.1.13 on 2026-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0009_kioskitem_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="kioskitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="kioskitem",
            name="uploaded_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
