# Generated by Django 4.1.13 on 2026-01-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0008_kioskitem_updated_at"),
        ("kiosk", "0009_kioskitem_duration"),
    ]

    operations = []
