# Generated by Django 4.1.13 on 2026-03-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0010_kioskitem_updated_at_alter_kioskitem_uploaded_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kioskitem",
            old_name="uploaded_date",
            new_name="created_at",
        ),
    ]
